import tweepy
import os
import datetime
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.patheffects as pe
from matplotlib import font_manager as fm
from logic import FishingPredictor, MAP_EXTENT, VISUAL_OFFSETS

# -------------------------------------------
# 1. 認証情報の読み込み
# -------------------------------------------
consumer_key = os.environ.get("TWITTER_API_KEY")
consumer_secret = os.environ.get("TWITTER_API_SECRET")
access_token = os.environ.get("TWITTER_ACCESS_TOKEN")
access_token_secret = os.environ.get("TWITTER_ACCESS_TOKEN_SECRET")

# -------------------------------------------
# 2. Twitter API 認証 (v1.1とv2の両方準備)
# -------------------------------------------
# v2: ツイート投稿用
client = tweepy.Client(
    consumer_key=consumer_key,
    consumer_secret=consumer_secret,
    access_token=access_token,
    access_token_secret=access_token_secret
)

# v1.1: 画像アップロード用
auth = tweepy.OAuth1UserHandler(
    consumer_key, consumer_secret, access_token, access_token_secret
)
api = tweepy.API(auth)

# -------------------------------------------
# 3. 画像生成関数 (Map作成)
# -------------------------------------------
def create_fishing_map(data, date_str):
    # フォント設定
    font_path = "ipaexg.ttf"
    if os.path.exists(font_path):
        fm.fontManager.addfont(font_path)
        plt.rcParams['font.family'] = 'IPAexGothic'
    
    # 図の作成
    fig, ax = plt.subplots(figsize=(8, 8))
    
    # 地図画像の読み込み (app.pyと同じ画像を使用)
    try:
        if os.path.exists('tokyo_bay_map.png'):
            img = mpimg.imread('tokyo_bay_map.png')
            ax.imshow(img, extent=MAP_EXTENT, aspect='auto', alpha=1.0, zorder=0)
        else:
            # 画像がない場合は水色背景
            ax.set_facecolor('#d4e6f1')
    except:
        ax.set_facecolor('#d4e6f1')

    # 範囲設定
    ax.set_xlim(MAP_EXTENT[0], MAP_EXTENT[1])
    ax.set_ylim(MAP_EXTENT[2], MAP_EXTENT[3])
    ax.axis('off')

    # タイトル表示
    ax.set_title(f"東京湾 釣果予報 {date_str}", fontsize=20, fontweight='bold', color='#0e4d92', pad=20)

    # ポイントのプロット
    for item in data:
        x, y = item['lon'], item['lat']
        # 位置微調整
        if item['name'] in VISUAL_OFFSETS:
            off = VISUAL_OFFSETS[item['name']]
            x += off['lon']; y += off['lat']
        
        cpue = item['total_cpue']
        size = 400 + (cpue * 60) # 少し大きめに
        colors = {'S':'#e74c3c', 'A':'#e67e22', 'B':'#f1c40f', 'C':'#2ecc71', 'D':'#95a5a6'}
        color = colors.get(item['rank'], 'gray')
        
        # ドット描画
        ax.scatter(x+0.003, y-0.003, s=size, c='black', alpha=0.15, zorder=9, edgecolors='none') # 影
        ax.scatter(x, y, s=size, c=color, alpha=0.9, edgecolors='white', linewidth=3, zorder=10) # 本体
        
        # ラベル描画
        label_txt = f"{item['name']}\n{cpue:.1f}"
        ax.text(x, y-0.015, label_txt, fontsize=14, fontweight='bold', ha='center', va='top', 
                 color='white', path_effects=[pe.withStroke(linewidth=4, foreground="#2c3e50")], zorder=11)

    # 著作権表記など
    ax.text(0.99, 0.01, "Generated by TokyoBayFishingAI", transform=ax.transAxes,
            fontsize=10, color='gray', ha='right', va='bottom')

    # ファイルとして保存
    filename = "forecast_map.png"
    plt.savefig(filename, bbox_inches='tight', dpi=100)
    plt.close()
    return filename

# -------------------------------------------
# 4. メイン処理
# -------------------------------------------
try:
    predictor = FishingPredictor()
    
    # 明日の日付
    tomorrow = datetime.date.today() + datetime.timedelta(days=1)
    date_str = tomorrow.strftime("%Y-%m-%d")
    disp_date = tomorrow.strftime("%m/%d")
    
    points = ["浦安", "若洲", "市原", "東扇島", "大黒", "磯子"]
    
    # 予測実行
    results = predictor.run_prediction(date_str, points)
    
    # 1位を取得
    sorted_results = sorted(results, key=lambda x: x['total_cpue'], reverse=True)
    best_spot = sorted_results[0]
    
    # 画像生成
    print("🎨 画像を生成中...")
    image_file = create_fishing_map(results, disp_date)
    
    # 画像アップロード (API v1.1)
    print("📤 画像をアップロード中...")
    media = api.media_upload(filename=image_file)
    
    # ツイート文の作成
    rank_emoji = {'S': '🔥', 'A': '😍', 'B': '😀', 'C': '😐', 'D': '😭'}.get(best_spot['rank'], '🤔')
    
    tweet_text = f"""📊 {disp_date} 東京湾釣果予報

明日のイチオシは【{best_spot['name']}】！
期待度: {best_spot['rank']} {rank_emoji} (指数: {best_spot['total_cpue']:.1f})

天気: {best_spot['weather']}
風速: {best_spot['wind']}m

👇 魚種別の詳細・他エリアはこちら
https://tokyo-bay-fishing-ai-ypd33onggtcjxnh69ryijz.streamlit.app/

#東京湾 #釣り #シーバス #アジング
"""

    # 投稿実行 (API v2)
    print("🐦 ツイート中...")
    client.create_tweet(text=tweet_text, media_ids=[media.media_id])
    
    print("✅ 画像付きツイート成功！")
    print(tweet_text)

except Exception as e:
    print(f"❌ エラーが発生しました: {e}")
